osx_image: xcode10.2
language: objective-c
cache:
  directories:
  - Carthage
  - Pods
before_install:
  - bundle install
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - travis_wait 60 carthage bootstrap --platform iOS --cache-builds
  - bundle exec pod repo update
script:
  - bundle exec fastlane rename name:NewProject
  - bundle exec pod install
  - set -o pipefail && xcodebuild -scheme Development -workspace NewProject.xcworkspace -destination 'platform=iOS Simulator,name=iPhone XS,OS=12.2' ONLY_ACTIVE_ARCH=NO | xcpretty
